// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFavoriteReq struct {
	Item string `json:"item"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ProfileResp struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Name  struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"name"`
	Favorites []string `json:"favorites"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     struct {
		First string `json:"first"`
		Last  string `json:"last"`
	} `json:"name"`
}
